version: '3.1'
services:

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
    depends_on:
      - courses
      - auth
    networks:
      - freedom_network
    
  db:
    image: postgres:11
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: freedom
    ports:
      - "5432:5432"
    networks:
      - freedom_network

  auth:
    build: ./auth-service
    container_name: auth
    ports:
      - "3001:3001"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_NAME: freedom
      DB_PORT: 5432
    volumes:
      - ./auth-service:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    networks:
      - freedom_network
 
  courses:
    build: ./course-service
    container_name: courses
    environment:
      - PORT=3002
    ports:
      - "3002:3002"
    networks:
      - freedom_network
    volumes:
      - ./course-service:/usr/src/app

  blog-service:
    build: ./blog-service
    container_name: blog
    ports:
      - "3003:3003"
    networks:
      - freedom_network
    volumes:
      - ./blog-service:/usr/src/app

  marketplace-service:
    build: ./marketplace-service
    container_name: marketplace
    ports:
      - "3004:3004"
    networks:
      - freedom_network
    volumes:
      - ./marketplace-service:/usr/src/app
    
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    networks:
      - freedom_network
    depends_on:
      - nginx

networks:
  freedom_network:
    driver: bridge