version: '3.1'
services:
 
  app:
    build: ./auth-service
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_NAME: freedom
      DB_PORT: 5432
    volumes:
      - ./auth-service/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    networks:
      - mynetwork
  
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: freedom
    ports:
      - "5432:5432"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge